apiVersion: 1

datasources:
  - name: Trading Bot Postgres
    uid: trading-bot-postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      postgresVersion: 1600
      sslmode: disable
      timescaledb: false
      maxOpenConns: 25
      maxIdleConns: 5
      connMaxLifetime: 14400
      defaultEditor: code
