#!/usr/bin/env bash
set -euo pipefail

# Fan out the backend env into the service-specific compose env files.
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_env="${1:-${repo_root}/backend/.env}"

if [[ ! -f "${source_env}" ]]; then
  echo "[compose-env] Missing source env: ${source_env}" >&2
  echo "[compose-env] Copy backend/.env.example to backend/.env first, or pass a different env file path." >&2
  exit 1
fi

set -a
sanitized_env="$(mktemp)"
trap 'rm -f "${sanitized_env}"' EXIT
tr -d '\r' < "${source_env}" > "${sanitized_env}"
# shellcheck disable=SC1090
source "${sanitized_env}"
set +a
rm -f "${sanitized_env}"
trap - EXIT

dashboard_env="${repo_root}/dashboard/compose.env"
grafana_env="${repo_root}/grafana/compose.env"

mkdir -p "$(dirname "${dashboard_env}")" "$(dirname "${grafana_env}")"

cat > "${dashboard_env}" <<EOF
# Generated by trading_bot/scripts/sync-compose-env.sh
# Source: ${source_env}
CONTROL_SECRET=${CONTROL_API_SECRET:-}
GRAFANA_BASE_URL=${GRAFANA_BASE_URL:-http://127.0.0.1:3400}
GRAFANA_EXECUTIVE_DASHBOARD_UID=${GRAFANA_EXECUTIVE_DASHBOARD_UID:-bot-executive-scorecard}
GRAFANA_ANALYST_DASHBOARD_UID=${GRAFANA_ANALYST_DASHBOARD_UID:-bot-analyst-insights}
GRAFANA_LIVE_DASHBOARD_UID=${GRAFANA_LIVE_DASHBOARD_UID:-bot-live-trade-monitor}
GRAFANA_TELEMETRY_DASHBOARD_UID=${GRAFANA_TELEMETRY_DASHBOARD_UID:-bot-telemetry-provider}
GRAFANA_CANDIDATE_DASHBOARD_UID=${GRAFANA_CANDIDATE_DASHBOARD_UID:-bot-candidate-funnel}
GRAFANA_POSITION_DASHBOARD_UID=${GRAFANA_POSITION_DASHBOARD_UID:-bot-position-pnl}
GRAFANA_CONFIG_DASHBOARD_UID=${GRAFANA_CONFIG_DASHBOARD_UID:-bot-config-impact}
GRAFANA_SOURCE_DASHBOARD_UID=${GRAFANA_SOURCE_DASHBOARD_UID:-bot-source-cohorts}
GRAFANA_RESEARCH_DASHBOARD_UID=${GRAFANA_RESEARCH_DASHBOARD_UID:-bot-research-dry-run}
EOF

cat > "${grafana_env}" <<EOF
# Generated by trading_bot/scripts/sync-compose-env.sh
# Source: ${source_env}
GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
GF_SERVER_ROOT_URL=${GRAFANA_BASE_URL:-http://127.0.0.1:3400}
POSTGRES_HOST=postgres:5432
POSTGRES_DB=${POSTGRES_DB:-trading_bot}
POSTGRES_USER=${POSTGRES_USER:-botuser}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-botpass}
EOF

echo "[compose-env] Wrote ${dashboard_env}"
echo "[compose-env] Wrote ${grafana_env}"
