param(
  [string]$SourceEnv = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($SourceEnv)) {
  $SourceEnv = Join-Path $repoRoot "backend/.env"
}

if (-not (Test-Path -LiteralPath $SourceEnv)) {
  Write-Error "[compose-env] Missing source env: $SourceEnv`n[compose-env] Copy backend/.env.example to backend/.env first, or pass a different env file path."
}

function Read-EnvFile {
  param([string]$Path)

  $values = @{}
  foreach ($line in Get-Content -LiteralPath $Path) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }

    $separator = $trimmed.IndexOf("=")
    if ($separator -lt 1) {
      continue
    }

    $key = $trimmed.Substring(0, $separator).Trim()
    $value = $trimmed.Substring($separator + 1).Trim()

    if ($value.Length -ge 2) {
      $quote = $value[0]
      if (($quote -eq '"' -or $quote -eq "'") -and $value[$value.Length - 1] -eq $quote) {
        $value = $value.Substring(1, $value.Length - 2)
      }
    }

    $values[$key] = $value
  }

  return $values
}

function Get-EnvValue {
  param(
    [hashtable]$Values,
    [string]$Name,
    [string]$Default
  )

  if ($Values.ContainsKey($Name) -and -not [string]::IsNullOrEmpty($Values[$Name])) {
    return $Values[$Name]
  }

  return $Default
}

$envValues = Read-EnvFile -Path $SourceEnv
$dashboardEnv = Join-Path $repoRoot "dashboard/compose.env"
$grafanaEnv = Join-Path $repoRoot "grafana/compose.env"

$dashboardLines = @(
  "# Generated by trading_bot/scripts/sync-compose-env.ps1"
  "# Source: $SourceEnv"
  "CONTROL_SECRET=$(Get-EnvValue -Values $envValues -Name 'CONTROL_API_SECRET' -Default '')"
  "GRAFANA_BASE_URL=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_BASE_URL' -Default 'http://127.0.0.1:3400')"
  "GRAFANA_EXECUTIVE_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_EXECUTIVE_DASHBOARD_UID' -Default 'bot-executive-scorecard')"
  "GRAFANA_ANALYST_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_ANALYST_DASHBOARD_UID' -Default 'bot-analyst-insights')"
  "GRAFANA_LIVE_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_LIVE_DASHBOARD_UID' -Default 'bot-live-trade-monitor')"
  "GRAFANA_TELEMETRY_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_TELEMETRY_DASHBOARD_UID' -Default 'bot-telemetry-provider')"
  "GRAFANA_CANDIDATE_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_CANDIDATE_DASHBOARD_UID' -Default 'bot-candidate-funnel')"
  "GRAFANA_POSITION_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_POSITION_DASHBOARD_UID' -Default 'bot-position-pnl')"
  "GRAFANA_CONFIG_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_CONFIG_DASHBOARD_UID' -Default 'bot-config-impact')"
  "GRAFANA_SOURCE_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_SOURCE_DASHBOARD_UID' -Default 'bot-source-cohorts')"
  "GRAFANA_RESEARCH_DASHBOARD_UID=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_RESEARCH_DASHBOARD_UID' -Default 'bot-research-dry-run')"
)

$grafanaLines = @(
  "# Generated by trading_bot/scripts/sync-compose-env.ps1"
  "# Source: $SourceEnv"
  "GF_SECURITY_ADMIN_USER=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_ADMIN_USER' -Default 'admin')"
  "GF_SECURITY_ADMIN_PASSWORD=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_ADMIN_PASSWORD' -Default 'admin')"
  "GF_SERVER_ROOT_URL=$(Get-EnvValue -Values $envValues -Name 'GRAFANA_BASE_URL' -Default 'http://127.0.0.1:3400')"
  "POSTGRES_HOST=postgres:5432"
  "POSTGRES_DB=$(Get-EnvValue -Values $envValues -Name 'POSTGRES_DB' -Default 'trading_bot')"
  "POSTGRES_USER=$(Get-EnvValue -Values $envValues -Name 'POSTGRES_USER' -Default 'botuser')"
  "POSTGRES_PASSWORD=$(Get-EnvValue -Values $envValues -Name 'POSTGRES_PASSWORD' -Default 'botpass')"
)

[System.IO.File]::WriteAllLines($dashboardEnv, $dashboardLines)
[System.IO.File]::WriteAllLines($grafanaEnv, $grafanaLines)

Write-Host "[compose-env] Wrote $dashboardEnv"
Write-Host "[compose-env] Wrote $grafanaEnv"
