#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_env="${1:-${repo_root}/backend/.env}"

if [[ ! -f "${source_env}" ]]; then
  echo "[compose-env] Missing source env: ${source_env}" >&2
  echo "[compose-env] Copy backend/.env.example to backend/.env first, or pass a different env file path." >&2
  exit 1
fi

trim_whitespace() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

strip_wrapping_quotes() {
  local value="$1"
  if [[ ${#value} -ge 2 ]]; then
    local first_char="${value:0:1}"
    local last_char="${value: -1}"
    if [[ "$first_char" == "$last_char" ]] && [[ "$first_char" == '"' || "$first_char" == "'" ]]; then
      printf '%s' "${value:1:${#value}-2}"
      return
    fi
  fi

  printf '%s' "$value"
}

get_env_value() {
  local key="$1"
  local default_value="$2"
  local line raw_value trimmed_key trimmed_value

  while IFS= read -r line || [[ -n "$line" ]]; do
    line="$(trim_whitespace "$line")"
    [[ -z "$line" || "${line:0:1}" == "#" ]] && continue
    [[ "$line" != *=* ]] && continue

    trimmed_key="$(trim_whitespace "${line%%=*}")"
    [[ "$trimmed_key" != "$key" ]] && continue

    raw_value="${line#*=}"
    trimmed_value="$(trim_whitespace "$raw_value")"
    strip_wrapping_quotes "$trimmed_value"
    return
  done < "${source_env}"

  printf '%s' "$default_value"
}

dashboard_env="${repo_root}/dashboard/compose.env"
grafana_env="${repo_root}/grafana/compose.env"

mkdir -p "$(dirname "${dashboard_env}")" "$(dirname "${grafana_env}")"

cat > "${dashboard_env}" <<EOF
# Generated by trading_bot/scripts/sync-compose-env.sh
# Source: ${source_env}
GRAFANA_BASE_URL=$(get_env_value "GRAFANA_BASE_URL" "http://127.0.0.1:3400")
GRAFANA_EXECUTIVE_DASHBOARD_UID=$(get_env_value "GRAFANA_EXECUTIVE_DASHBOARD_UID" "bot-executive-scorecard")
GRAFANA_ANALYST_DASHBOARD_UID=$(get_env_value "GRAFANA_ANALYST_DASHBOARD_UID" "bot-analyst-insights")
GRAFANA_LIVE_DASHBOARD_UID=$(get_env_value "GRAFANA_LIVE_DASHBOARD_UID" "bot-live-trade-monitor")
GRAFANA_TELEMETRY_DASHBOARD_UID=$(get_env_value "GRAFANA_TELEMETRY_DASHBOARD_UID" "bot-telemetry-provider")
GRAFANA_CANDIDATE_DASHBOARD_UID=$(get_env_value "GRAFANA_CANDIDATE_DASHBOARD_UID" "bot-candidate-funnel")
GRAFANA_POSITION_DASHBOARD_UID=$(get_env_value "GRAFANA_POSITION_DASHBOARD_UID" "bot-position-pnl")
GRAFANA_CONFIG_DASHBOARD_UID=$(get_env_value "GRAFANA_CONFIG_DASHBOARD_UID" "bot-config-impact")
GRAFANA_SOURCE_DASHBOARD_UID=$(get_env_value "GRAFANA_SOURCE_DASHBOARD_UID" "bot-source-cohorts")
GRAFANA_RESEARCH_DASHBOARD_UID=$(get_env_value "GRAFANA_RESEARCH_DASHBOARD_UID" "bot-research-dry-run")
EOF

cat > "${grafana_env}" <<EOF
# Generated by trading_bot/scripts/sync-compose-env.sh
# Source: ${source_env}
GF_SECURITY_ADMIN_USER=$(get_env_value "GRAFANA_ADMIN_USER" "admin")
GF_SECURITY_ADMIN_PASSWORD=$(get_env_value "GRAFANA_ADMIN_PASSWORD" "admin")
GF_SERVER_ROOT_URL=$(get_env_value "GRAFANA_BASE_URL" "http://127.0.0.1:3400")
POSTGRES_HOST=postgres:5432
POSTGRES_DB=$(get_env_value "POSTGRES_DB" "trading_bot")
POSTGRES_USER=$(get_env_value "POSTGRES_USER" "botuser")
POSTGRES_PASSWORD=$(get_env_value "POSTGRES_PASSWORD" "botpass")
EOF

echo "[compose-env] Wrote ${dashboard_env}"
echo "[compose-env] Wrote ${grafana_env}"
