export const chartColors = {
  win: "var(--chart-positive)",
  loss: "var(--chart-negative)",
  neutral: "var(--chart-neutral)",
  warning: "var(--chart-warning)",
  muted: "var(--chart-text-muted)",
  gridLine: "var(--chart-grid)",
  tooltipBg: "var(--chart-surface)",
  tooltipBorder: "var(--chart-surface-border)",
  tooltipText: "var(--chart-text)",
  capital: "var(--chart-capital)",
  s1: "var(--chart-strategy-s1)",
  s2: "var(--chart-strategy-s2)",
  s3: "var(--chart-strategy-s3)",
} as const;
