-- AlterTable DailyStats
ALTER TABLE "DailyStats" ADD COLUMN "profitFactor" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyStats" ADD COLUMN "expectancy" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyStats" ADD COLUMN "avgHoldMinutes" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyStats" ADD COLUMN "trancheT1Pct" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyStats" ADD COLUMN "trancheT2Pct" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyStats" ADD COLUMN "trancheT3Pct" DOUBLE PRECISION NOT NULL DEFAULT 0;
